// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApplication.Models;

#nullable disable

namespace QuizApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuizApplication.Models.Choice", b =>
                {
                    b.Property<int>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChoiceId"), 1L, 1);

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChoicesId")
                        .HasColumnType("int");

                    b.Property<bool>("FacturalStatement")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChoiceId");

                    b.HasIndex("ChoicesId");

                    b.ToTable("Choice");
                });

            modelBuilder.Entity("QuizApplication.Models.Choices", b =>
                {
                    b.Property<int>("ChoicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChoicesId"), 1L, 1);

                    b.Property<int>("CurrentQuestionId")
                        .HasColumnType("int");

                    b.HasKey("ChoicesId");

                    b.ToTable("choices");
                });

            modelBuilder.Entity("QuizApplication.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"), 1L, 1);

                    b.Property<int?>("ChoicesId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionHeading")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("ChoicesId");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("QuizApplication.Models.Choice", b =>
                {
                    b.HasOne("QuizApplication.Models.Choices", null)
                        .WithMany("ChoicesOfQuestion")
                        .HasForeignKey("ChoicesId");
                });

            modelBuilder.Entity("QuizApplication.Models.Question", b =>
                {
                    b.HasOne("QuizApplication.Models.Choices", "Choices")
                        .WithMany()
                        .HasForeignKey("ChoicesId");

                    b.Navigation("Choices");
                });

            modelBuilder.Entity("QuizApplication.Models.Choices", b =>
                {
                    b.Navigation("ChoicesOfQuestion");
                });
#pragma warning restore 612, 618
        }
    }
}
